name: Unit tests

on:
  push:
    branches:
      - 'feat-*/**'
  pull_request:
    branches:
      - 'feat-*/**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Execute tests
      run: |
        ./gradlew test
